name: dgc_demo_project
description: "An assignment project for DGC recruitment"

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.7.2
  get_storage: ^2.1.1

  #  Storage
  flutter_secure_storage: ^9.2.4

  #  Widgets
  flutter_svg: ^2.2.2
  shimmer: ^3.0.0
  gap: ^3.0.1
  flutter_form_builder: ^10.2.0
  flutter_picker: ^2.1.0
  duration_picker: ^1.1.1
  fl_chart: ^0.69.0

  #  Image
  extended_image: ^10.0.1

  #  Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  #  Utils
  permission_handler: ^12.0.1
  intl: ^0.20.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.2
  open_filex: ^4.7.0
  flutter_exit_app: ^2.0.0
  flutter_displaymode: ^0.7.0
  clipboard: ^2.0.2
  fluttertoast: ^9.0.0
  package_info_plus: ^9.0.0
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9


flutter:


  uses-material-design: true

  fonts:
    - family: Nokora
      fonts:
        - asset: assets/fonts/nokora/Nokora-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/nokora/Nokora-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/nokora/Nokora-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/nokora/Nokora-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/nokora/Nokora-Black.ttf
          weight: 900
          style: normal
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/
    - assets/icons/
